# Generated by Django 5.2.4 on 2026-02-28 16:25

from django.db import migrations


def search_new_building(apps, schema_editor):
    Flat = apps.get_model('property', 'Flat')
    Flat.objects.filter(construction_year__gte=2015).update(new_building=True)
    Flat.objects.filter(construction_year__lt=2015).update(new_building=False)
    Flat.save


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0005_alter_flat_new_building'),
    ]

    operations = [
        migrations.RunPython(search_new_building),
    ]
