# Generated by Django 5.2.4 on 2026-02-28 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0008_alter_complaint_complainant'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='description',
            field=models.TextField(blank=True, verbose_name='Текст жалобы'),
        ),
    ]
