# Generated by Django 5.2.4 on 2026-03-14 15:13
import phonenumbers
from django.db import migrations


def filling_numbers(apps, schema_editor):
    Flat = apps.get_model('property', 'Flat')

    flat_objects = Flat.objects.all()
    for flat_object in flat_objects.iterator():
        parsed_phonenumber = phonenumbers.parse(flat_object.owners_phonenumber, 'RU')
        if parsed_phonenumber and phonenumbers.is_valid_number(parsed_phonenumber):
            pure_number = phonenumbers.format_number(parsed_phonenumber, phonenumbers.PhoneNumberFormat.E164)
            flat_object.owner_pure_phone = pure_number
            flat_object.save(update_fields=['owner_pure_phone'])


def backward(apps, schema_editor):
    Flat = apps.get_model('property', 'Flat')
    Flat.objects.all().update(owner_pure_phone=None)


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0013_alter_flat_liked_by'),
    ]

    operations = [
        migrations.RunPython(filling_numbers, backward),
    ]
