# Generated by Django 5.2.4 on 2026-03-21 15:50

from django.db import migrations


def migrate_owners_to_owner_model(apps, schema_editor):
    Flat = apps.get_model('property', 'Flat')
    Owner = apps.get_model('property', 'Owner')

    flat_objects = Flat.objects.all()
    for flat_object in flat_objects:
        Owner.objects.get_or_create(owner=flat_object.owner, owners_phonenumber=flat_object.owners_phonenumber, owner_pure_phone=flat_object.owner_pure_phone)


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0016_alter_owner_owner_pure_phone'),
    ]

    operations = [
        migrations.RunPython(migrate_owners_to_owner_model),
    ]
