# Generated by Django 5.2.4 on 2026-03-21 16:37

from django.db import migrations


def apartment_owners(apps, schema_editor):
    Flat = apps.get_model('property', 'Flat')
    Owner = apps.get_model('property', 'Owner')

    owner_objects = Owner.objects.all()
    for owner_object in owner_objects:
        owner_object.apartaments.set(Flat.objects.filter(owner=owner_object.owner))


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0017_auto_20260321_1850'),
    ]

    operations = [
        migrations.RunPython(apartment_owners),
    ]
