# Generated by Django 5.2.4 on 2026-04-05 10:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0019_remove_flat_owner_remove_flat_owner_pure_phone_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='owner',
            old_name='owner',
            new_name='owner_name',
        ),
    ]
