# Generated by Django 5.2.4 on 2026-04-11 15:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0020_rename_owner_owner_owner_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='owner',
            old_name='apartaments',
            new_name='apartments',
        ),
    ]
