# Generated by Django 6.0.5 on 2026-05-10 11:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0023_alter_complaint_apartament_complained_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaint',
            name='apartament_complained',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='complaints', to='property.flat', verbose_name='Квартира, на которую подана жалоба'),
        ),
    ]
