# Generated by Django 6.0.5 on 2026-05-10 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0024_alter_complaint_apartament_complained'),
    ]

    operations = [
        migrations.RenameField(
            model_name='complaint',
            old_name='apartament_complained',
            new_name='apartament',
        ),
        migrations.RenameField(
            model_name='owner',
            old_name='owners_phonenumber',
            new_name='phonenumber',
        ),
        migrations.RenameField(
            model_name='owner',
            old_name='owner_pure_phone',
            new_name='pure_phone',
        ),
        migrations.RemoveField(
            model_name='owner',
            name='owner_name',
        ),
        migrations.AddField(
            model_name='owner',
            name='name',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='ФИО владельца:'),
        ),
    ]
