# Generated by Django 6.0.5 on 2026-05-30 15:24

import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0025_rename_apartament_complained_complaint_apartament_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='owner',
            old_name='apartments',
            new_name='apartaments',
        ),
        migrations.AddField(
            model_name='flat',
            name='owner',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='ФИО владельца'),
        ),
        migrations.AddField(
            model_name='flat',
            name='owner_pure_phone',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, region=None, verbose_name='Нормализованные номер владельца'),
        ),
        migrations.AddField(
            model_name='flat',
            name='owners_phonenumber',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Номер владельца'),
        ),
    ]
