# Generated by Django 6.0.5 on 2026-05-30 15:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0026_rename_apartments_owner_apartaments_flat_owner_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flat',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='flat',
            name='owner_pure_phone',
        ),
        migrations.RemoveField(
            model_name='flat',
            name='owners_phonenumber',
        ),
    ]
